import React, { createContext, useContext, useEffect, useState } from 'react';

export type LanguageCode = 'English' | 'Spanish' | 'German' | 'Arabic' | 'Urdu';

interface LanguageContextValue {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const STORAGE_KEY = 'beloz-selected-language';
const DEFAULT_LANGUAGE: LanguageCode = 'English';

export const uiLabels: Record<LanguageCode, any> = {
  English: {
    sidebar: {
      user: 'User',
      history: 'History',
      languages: 'Language & Rate',
      lines: 'Line and Extensions',
    },
    header: {
      notifications: 'Notifications',
      myProfile: 'My Profile',
      logout: 'Logout',
      admin: 'Admin',
    },
    notificationItems: [
      'New interpreter request pending',
      'CSR role change approved',
      'Language rate updated',
    ],
    pages: {
      languagesPage: {
        title: 'Language & Rate',
        subtitle: 'Select a language to apply to this page.',
        button: 'Add Language',
        createHeader: 'Add New Language',
        tableHeaders: {
          language: 'Language',
          rate: 'Rate / Min',
          status: 'Status',
        },
        statusMap: {
          Active: 'Active',
          Inactive: 'Inactive',
        },
      },
      linesPage: {
        title: 'Line and Extensions',
        button: 'Add Line',
        createHeader: 'New Line',
        tableHeaders: {
          lineName: 'Line Name',
          extension: 'Extension',
          assignedTo: 'Assigned To',
          status: 'Status',
        },
        menuItems: {
          salesLine: 'Sales Line',
          supportLine: 'Support Line',
        },
      },
      usersPage: {
        title: 'User',
        filterAll: 'All',
        filterInterpreter: 'Interpreter',
        filterCSR: 'CSR',
        filterCustomer: 'Customer',
        filterWebManager: 'Web Manager',
        createButton: 'Create New User',
        createHeader: 'Create New',
        newInterpreter: 'New Interpreter',
        newCSR: 'New CSR',
        newManager: 'New Manager',
        newCustomer: 'New Customer',
        tableHeaders: {
          name: 'Name',
          email: 'Email',
          phone: 'Phone',
          role: 'Role',
          extension: 'Extension',
          language: 'Language',
          status: 'Status',
          edit: 'Edit',
          delete: 'Delete',
        },
        formLabels: {
          fullName: 'Full Name',
          emailAddress: 'Email Address',
          phoneNumber: 'Phone Number',
          preferredLanguage: 'Preferred Language',
          skill: 'Skill',
          department: 'Department',
          enterprise: 'Enterprise',
          gender: 'Gender',
          requestGender: 'Request Gender',
        },
        buttons: {
          cancel: 'Cancel',
          submit: 'Submit',
          back: 'Back',
          submitRequest: 'Submit Request',
        },
        toast: {
          interpreter: 'Interpreter request submitted',
          csr: 'CSR request submitted',
          manager: 'Manager request submitted',
          customer: 'Customer request submitted',
        },
      },
      historyPage: {
        pageTitle: {
          interpreter: 'Interpreter’s History',
          csr: 'CSR’s History',
          customer: 'Customer’s History',
          webManager: 'Web Manager',
          mobileInterpreter: 'Mobile Interpreter History',
          mobileManager: 'Mobile Manager History',
        },
        historyFilterButton: 'History',
        dropdown: {
          interpreter: 'Interpreter’s History',
          csr: 'CSR’s History',
          customer: 'Customer’s History',
          webManager: 'Web Manager',
          mobileInterpreter: 'Mobile Interpreter History',
          mobileManager: 'Mobile Manager History',
        },
        tableHeaders: {
          enterprise: 'Enterprise',
          dateTime: 'Date & Time',
          accessCode: 'Access Code',
          phone: 'Phone',
          language: 'Language',
          duration: 'Duration',
          edit: 'Edit',
          delete: 'Delete',
        },
        editModal: {
          title: 'Edit history record',
          enterprise: 'Enterprise',
          dateTime: 'Date & Time',
          accessCode: 'Access Code',
          phone: 'Phone',
          language: 'Language',
          duration: 'Duration',
          cancel: 'Cancel',
          saveChanges: 'Save Changes',
        },
        pagination: {
          page: 'Page',
        },
      },
      addInterpreterPage: {
        title: 'Add New Interpreter / CSR',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        requestType: 'Request Type',
        preferredLanguage: 'Preferred Language',
        skill: 'Skill',
        requestGender: 'Request Gender',
        back: 'Back',
        submitRequest: 'Submit Request',
      },
      addCSRPage: {
        title: 'Add New CSR',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        gender: 'Gender',
        back: 'Back',
        addCSR: 'Add CSR',
      },
      addManagerPage: {
        title: 'Add New Manager',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        department: 'Department',
        language: 'Language',
        gender: 'Gender',
        back: 'Back',
        addManager: 'Add Manager',
      },
      addCustomerPage: {
        title: 'Add New Customer',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        enterprise: 'Enterprise',
        preferredLanguage: 'Preferred Language',
        back: 'Back',
        addCustomer: 'Add Customer',
      },
      editInterpreterPage: {
        title: 'Edit Interpreter / CSR',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        requestGender: 'Request Gender',
        back: 'Back',
        saveChanges: 'Save Changes',
      },
      editCSRPage: {
        title: 'Edit CSR',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        gender: 'Gender',
        back: 'Back',
        saveChanges: 'Save Changes',
      },
      editManagerPage: {
        title: 'Edit Manager',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        department: 'Department',
        language: 'Language',
        gender: 'Gender',
        back: 'Back',
        saveManager: 'Save Manager',
      },
    },
  },
  Spanish: {
    sidebar: {
      user: 'Usuario',
      history: 'Historial',
      languages: 'Idioma y tarifa',
      lines: 'Líneas y extensiones',
    },
    header: {
      notifications: 'Notificaciones',
      myProfile: 'Mi perfil',
      logout: 'Cerrar sesión',
      admin: 'Administrador',
    },
    notificationItems: [
      'Solicitud de intérprete nueva pendiente',
      'Cambio de rol CSR aprobado',
      'Tarifa de idioma actualizada',
    ],
    pages: {
      languagesPage: {
        title: 'Idioma y tarifa',
        subtitle: 'Seleccione un idioma para aplicar en esta página.',
        button: 'Agregar idioma',
        createHeader: 'Agregar nuevo idioma',
        tableHeaders: {
          language: 'Idioma',
          rate: 'Tarifa / Min',
          status: 'Estado',
        },
        statusMap: {
          Active: 'Activo',
          Inactive: 'Inactivo',
        },
      },
      linesPage: {
        title: 'Líneas y extensiones',
        button: 'Agregar línea',
        createHeader: 'Nueva línea',
        tableHeaders: {
          lineName: 'Nombre de la línea',
          extension: 'Extensión',
          assignedTo: 'Asignado a',
          status: 'Estado',
        },
        menuItems: {
          salesLine: 'Línea de ventas',
          supportLine: 'Línea de soporte',
        },
      },
      usersPage: {
        title: 'Usuario',
        filterAll: 'Todo',
        filterInterpreter: 'Intérprete',
        filterCSR: 'CSR',
        filterCustomer: 'Cliente',
        filterWebManager: 'Administrador web',
        createButton: 'Crear nuevo usuario',
        createHeader: 'Crear nuevo',
        newInterpreter: 'Nuevo intérprete',
        newCSR: 'Nuevo CSR',
        newManager: 'Nuevo gerente',
        newCustomer: 'Nuevo cliente',
        tableHeaders: {
          name: 'Nombre',
          email: 'Correo',
          phone: 'Teléfono',
          role: 'Rol',
          extension: 'Extensión',
          language: 'Idioma',
          status: 'Estado',
          edit: 'Editar',
          delete: 'Eliminar',
        },
        formLabels: {
          fullName: 'Nombre completo',
          emailAddress: 'Correo electrónico',
          phoneNumber: 'Número de teléfono',
          preferredLanguage: 'Idioma preferido',
          skill: 'Habilidad',
          department: 'Departamento',
          enterprise: 'Empresa',
          gender: 'Género',
          requestGender: 'Género solicitado',
        },
        buttons: {
          cancel: 'Cancelar',
          submit: 'Enviar',
          back: 'Atrás',
          submitRequest: 'Enviar solicitud',
        },
        toast: {
          interpreter: 'Solicitud de intérprete enviada',
          csr: 'Solicitud de CSR enviada',
          manager: 'Solicitud de gerente enviada',
          customer: 'Solicitud de cliente enviada',
        },
      },
      historyPage: {
        pageTitle: {
          interpreter: 'Historial de intérprete',
          csr: 'Historial de CSR',
          customer: 'Historial de cliente',
          webManager: 'Administrador web',
          mobileInterpreter: 'Historial de intérprete móvil',
          mobileManager: 'Historial de gerente móvil',
        },
        historyFilterButton: 'Historial',
        dropdown: {
          interpreter: 'Historial de intérprete',
          csr: 'Historial de CSR',
          customer: 'Historial de cliente',
          webManager: 'Administrador web',
          mobileInterpreter: 'Historial de intérprete móvil',
          mobileManager: 'Historial de gerente móvil',
        },
        tableHeaders: {
          enterprise: 'Empresa',
          dateTime: 'Fecha y hora',
          accessCode: 'Código de acceso',
          phone: 'Teléfono',
          language: 'Idioma',
          duration: 'Duración',
          edit: 'Editar',
          delete: 'Eliminar',
        },
        editModal: {
          title: 'Editar registro de historial',
          enterprise: 'Empresa',
          dateTime: 'Fecha y hora',
          accessCode: 'Código de acceso',
          phone: 'Teléfono',
          language: 'Idioma',
          duration: 'Duración',
          cancel: 'Cancelar',
          saveChanges: 'Guardar cambios',
        },
        pagination: {
          page: 'Página',
        },
      },
      addInterpreterPage: {
        title: 'Agregar nuevo intérprete / CSR',
        fullName: 'Nombre completo',
        emailAddress: 'Correo electrónico',
        phoneNumber: 'Número de teléfono',
        requestType: 'Tipo de solicitud',
        preferredLanguage: 'Idioma preferido',
        skill: 'Habilidad',
        requestGender: 'Género solicitado',
        back: 'Atrás',
        submitRequest: 'Enviar solicitud',
      },
      addCSRPage: {
        title: 'Agregar nuevo CSR',
        fullName: 'Nombre completo',
        emailAddress: 'Correo electrónico',
        phoneNumber: 'Número de teléfono',
        language: 'Idioma',
        skill: 'Habilidad',
        gender: 'Género',
        back: 'Atrás',
        addCSR: 'Agregar CSR',
      },
      addManagerPage: {
        title: 'Agregar nuevo gerente',
        fullName: 'Nombre completo',
        emailAddress: 'Correo electrónico',
        phoneNumber: 'Número de teléfono',
        department: 'Departamento',
        language: 'Idioma',
        gender: 'Género',
        back: 'Atrás',
        addManager: 'Agregar gerente',
      },
      addCustomerPage: {
        title: 'Agregar nuevo cliente',
        fullName: 'Nombre completo',
        emailAddress: 'Correo electrónico',
        phoneNumber: 'Número de teléfono',
        enterprise: 'Empresa',
        preferredLanguage: 'Idioma preferido',
        back: 'Atrás',
        addCustomer: 'Agregar cliente',
      },
      editInterpreterPage: {
        title: 'Editar intérprete / CSR',
        fullName: 'Nombre completo',
        emailAddress: 'Correo',
        phoneNumber: 'Número de teléfono',
        language: 'Idioma',
        skill: 'Habilidad',
        requestGender: 'Género solicitado',
        back: 'Atrás',
        saveChanges: 'Guardar cambios',
      },
      editCSRPage: {
        title: 'Editar CSR',
        fullName: 'Nombre completo',
        emailAddress: 'Correo',
        phoneNumber: 'Número de teléfono',
        language: 'Idioma',
        skill: 'Habilidad',
        gender: 'Género',
        back: 'Atrás',
        saveChanges: 'Guardar cambios',
      },
      editManagerPage: {
        title: 'Editar gerente',
        fullName: 'Nombre completo',
        emailAddress: 'Correo',
        phoneNumber: 'Número de teléfono',
        department: 'Departamento',
        language: 'Idioma',
        gender: 'Género',
        back: 'Atrás',
        saveManager: 'Guardar gerente',
      },
    },
  },
  German: {
    sidebar: {
      user: 'Benutzer',
      history: 'Verlauf',
      languages: 'Sprache & Tarif',
      lines: 'Leitungen & Durchwahlen',
    },
    header: {
      notifications: 'Benachrichtigungen',
      myProfile: 'Mein Profil',
      logout: 'Abmelden',
      admin: 'Admin',
    },
    notificationItems: [
      'Neue Dolmetscheranfrage ausstehend',
      'CSR-Rollenänderung genehmigt',
      'Sprachpreis aktualisiert',
    ],
    pages: {
      languagesPage: {
        title: 'Sprache & Tarif',
        subtitle: 'Wählen Sie eine Sprache für diese Seite aus.',
        button: 'Sprache hinzufügen',
        createHeader: 'Neue Sprache hinzufügen',
        tableHeaders: {
          language: 'Sprache',
          rate: 'Tarif / Min',
          status: 'Status',
        },
        statusMap: {
          Active: 'Aktiv',
          Inactive: 'Inaktiv',
        },
      },
      linesPage: {
        title: 'Leitungen & Durchwahlen',
        button: 'Leitung hinzufügen',
        createHeader: 'Neue Leitung',
        tableHeaders: {
          lineName: 'Leitungsname',
          extension: 'Durchwahl',
          assignedTo: 'Zugewiesen an',
          status: 'Status',
        },
        menuItems: {
          salesLine: 'Verkaufslinie',
          supportLine: 'Support-Linie',
        },
      },
      usersPage: {
        title: 'Benutzer',
        filterAll: 'Alle',
        filterInterpreter: 'Dolmetscher',
        filterCSR: 'CSR',
        filterCustomer: 'Kunde',
        filterWebManager: 'Web-Manager',
        createButton: 'Neuen Benutzer erstellen',
        createHeader: 'Neu erstellen',
        newInterpreter: 'Neuer Dolmetscher',
        newCSR: 'Neuer CSR',
        newManager: 'Neuer Manager',
        newCustomer: 'Neuer Kunde',
        tableHeaders: {
          name: 'Name',
          email: 'E-Mail',
          phone: 'Telefon',
          role: 'Rolle',
          extension: 'Durchwahl',
          language: 'Sprache',
          status: 'Status',
          edit: 'Bearbeiten',
          delete: 'Löschen',
        },
        formLabels: {
          fullName: 'Vollständiger Name',
          emailAddress: 'E-Mail-Adresse',
          phoneNumber: 'Telefonnummer',
          preferredLanguage: 'Bevorzugte Sprache',
          skill: 'Fähigkeit',
          department: 'Abteilung',
          enterprise: 'Unternehmen',
          gender: 'Geschlecht',
          requestGender: 'Gewünschtes Geschlecht',
        },
        buttons: {
          cancel: 'Abbrechen',
          submit: 'Absenden',
          back: 'Zurück',
          submitRequest: 'Anfrage absenden',
        },
        toast: {
          interpreter: 'Dolmetscher-Anfrage gesendet',
          csr: 'CSR-Anfrage gesendet',
          manager: 'Manager-Anfrage gesendet',
          customer: 'Kunden-Anfrage gesendet',
        },
      },
      historyPage: {
        pageTitle: {
          interpreter: 'Interpreter’s History',
          csr: 'CSR’s History',
          customer: 'Customer’s History',
          webManager: 'Web Manager',
          mobileInterpreter: 'Mobile Interpreter History',
          mobileManager: 'Mobile Manager History',
        },
        historyFilterButton: 'History',
        dropdown: {
          interpreter: 'Interpreter’s History',
          csr: 'CSR’s History',
          customer: 'Customer’s History',
          webManager: 'Web Manager',
          mobileInterpreter: 'Mobile Interpreter History',
          mobileManager: 'Mobile Manager History',
        },
        tableHeaders: {
          enterprise: 'Enterprise',
          dateTime: 'Date & Time',
          accessCode: 'Access Code',
          phone: 'Phone',
          language: 'Language',
          duration: 'Duration',
          edit: 'Edit',
          delete: 'Delete',
        },
        editModal: {
          title: 'Edit history record',
          enterprise: 'Enterprise',
          dateTime: 'Date & Time',
          accessCode: 'Access Code',
          phone: 'Phone',
          language: 'Language',
          duration: 'Duration',
          cancel: 'Cancel',
          saveChanges: 'Save Changes',
        },
        pagination: {
          page: 'Page',
        },
      },
      addInterpreterPage: {
        title: 'Add New Interpreter / CSR',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        requestType: 'Request Type',
        preferredLanguage: 'Preferred Language',
        skill: 'Skill',
        requestGender: 'Request Gender',
        back: 'Back',
        submitRequest: 'Submit Request',
      },
      addCSRPage: {
        title: 'Add New CSR',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        gender: 'Gender',
        back: 'Back',
        addCSR: 'Add CSR',
      },
      addManagerPage: {
        title: 'Add New Manager',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        department: 'Department',
        language: 'Language',
        gender: 'Gender',
        back: 'Back',
        addManager: 'Add Manager',
      },
      addCustomerPage: {
        title: 'Add New Customer',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        enterprise: 'Enterprise',
        preferredLanguage: 'Preferred Language',
        back: 'Back',
        addCustomer: 'Add Customer',
      },
      editInterpreterPage: {
        title: 'Edit Interpreter / CSR',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        requestGender: 'Request Gender',
        back: 'Back',
        saveChanges: 'Save Changes',
      },
      editCSRPage: {
        title: 'Edit CSR',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        gender: 'Gender',
        back: 'Back',
        saveChanges: 'Save Changes',
      },
      editManagerPage: {
        title: 'Edit Manager',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        department: 'Department',
        language: 'Language',
        gender: 'Gender',
        back: 'Back',
        saveManager: 'Save Manager',
      },
    },
  },
  Arabic: {
    sidebar: {
      user: 'User',
      history: 'History',
      languages: 'Language & Rate',
      lines: 'Line and Extensions',
    },
    header: {
      notifications: 'Notifications',
      myProfile: 'My Profile',
      logout: 'Logout',
      admin: 'Admin',
    },
    notificationItems: [
      'New interpreter request pending',
      'CSR role change approved',
      'Language rate updated',
    ],
    pages: {
      languagesPage: {
        title: 'Language & Rate',
        subtitle: 'Select a language to apply to this page.',
        button: 'Add Language',
        createHeader: 'Add New Language',
        tableHeaders: {
          language: 'Language',
          rate: 'Rate / Min',
          status: 'Status',
        },
        statusMap: {
          Active: 'Active',
          Inactive: 'Inactive',
        },
      },
      linesPage: {
        title: 'Line and Extensions',
        button: 'Add Line',
        createHeader: 'New Line',
        tableHeaders: {
          lineName: 'Line Name',
          extension: 'Extension',
          assignedTo: 'Assigned To',
          status: 'Status',
        },
        menuItems: {
          salesLine: 'Sales Line',
          supportLine: 'Support Line',
        },
      },
      usersPage: {
        title: 'User',
        filterAll: 'All',
        filterInterpreter: 'Interpreter',
        filterCSR: 'CSR',
        filterCustomer: 'Customer',
        filterWebManager: 'Web Manager',
        createButton: 'Create New User',
        createHeader: 'Create New',
        newInterpreter: 'New Interpreter',
        newCSR: 'New CSR',
        newManager: 'New Manager',
        newCustomer: 'New Customer',
        tableHeaders: {
          name: 'Name',
          email: 'Email',
          phone: 'Phone',
          role: 'Role',
          extension: 'Extension',
          language: 'Language',
          status: 'Status',
          edit: 'Edit',
          delete: 'Delete',
        },
        formLabels: {
          fullName: 'Full Name',
          emailAddress: 'Email Address',
          phoneNumber: 'Phone Number',
          preferredLanguage: 'Preferred Language',
          skill: 'Skill',
          department: 'Department',
          enterprise: 'Enterprise',
          gender: 'Gender',
          requestGender: 'Request Gender',
        },
        buttons: {
          cancel: 'Cancel',
          submit: 'Submit',
          back: 'Back',
          submitRequest: 'Submit Request',
        },
        toast: {
          interpreter: 'Interpreter request submitted',
          csr: 'CSR request submitted',
          manager: 'Manager request submitted',
          customer: 'Customer request submitted',
        },
      },
      historyPage: {
        pageTitle: {
          interpreter: 'Interpreter’s History',
          csr: 'CSR’s History',
          customer: 'Customer’s History',
          webManager: 'Web Manager',
          mobileInterpreter: 'Mobile Interpreter History',
          mobileManager: 'Mobile Manager History',
        },
        historyFilterButton: 'History',
        dropdown: {
          interpreter: 'Interpreter’s History',
          csr: 'CSR’s History',
          customer: 'Customer’s History',
          webManager: 'Web Manager',
          mobileInterpreter: 'Mobile Interpreter History',
          mobileManager: 'Mobile Manager History',
        },
        tableHeaders: {
          enterprise: 'Enterprise',
          dateTime: 'Date & Time',
          accessCode: 'Access Code',
          phone: 'Phone',
          language: 'Language',
          duration: 'Duration',
          edit: 'Edit',
          delete: 'Delete',
        },
        editModal: {
          title: 'Edit history record',
          enterprise: 'Enterprise',
          dateTime: 'Date & Time',
          accessCode: 'Access Code',
          phone: 'Phone',
          language: 'Language',
          duration: 'Duration',
          cancel: 'Cancel',
          saveChanges: 'Save Changes',
        },
        pagination: {
          page: 'Page',
        },
      },
      addInterpreterPage: {
        title: 'Add New Interpreter / CSR',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        requestType: 'Request Type',
        preferredLanguage: 'Preferred Language',
        skill: 'Skill',
        requestGender: 'Request Gender',
        back: 'Back',
        submitRequest: 'Submit Request',
      },
      addCSRPage: {
        title: 'Add New CSR',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        gender: 'Gender',
        back: 'Back',
        addCSR: 'Add CSR',
      },
      addManagerPage: {
        title: 'Add New Manager',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        department: 'Department',
        language: 'Language',
        gender: 'Gender',
        back: 'Back',
        addManager: 'Add Manager',
      },
      addCustomerPage: {
        title: 'Add New Customer',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        enterprise: 'Enterprise',
        preferredLanguage: 'Preferred Language',
        back: 'Back',
        addCustomer: 'Add Customer',
      },
      editInterpreterPage: {
        title: 'Edit Interpreter / CSR',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        requestGender: 'Request Gender',
        back: 'Back',
        saveChanges: 'Save Changes',
      },
      editCSRPage: {
        title: 'Edit CSR',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        gender: 'Gender',
        back: 'Back',
        saveChanges: 'Save Changes',
      },
      editManagerPage: {
        title: 'Edit Manager',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        department: 'Department',
        language: 'Language',
        gender: 'Gender',
        back: 'Back',
        saveManager: 'Save Manager',
      },
    },
  },
  Urdu: {
    sidebar: {
      user: 'صارف',
      history: 'تاریخ',
      languages: 'زبان اور نرخ',
      lines: 'لائن اور ایکسٹینشن',
    },
    header: {
      notifications: 'اطلاعات',
      myProfile: 'میرا پروفائل',
      logout: 'لاگ آؤٹ',
      admin: 'ایڈمن',
    },
    notificationItems: [
      'نیا مترجم درخواست زیر التواء',
      'CSR رول تبدیلی منظور ہوگئی',
      'زبان کی قیمت اپ ڈیٹ ہو گئی',
    ],
    pages: {
      languagesPage: {
        title: 'زبان اور نرخ',
        subtitle: 'اس صفحہ پر لاگو کرنے کے لئے زبان منتخب کریں۔',
        button: 'زبان شامل کریں',
        createHeader: 'نئی زبان شامل کریں',
        tableHeaders: {
          language: 'زبان',
          rate: 'نرخ / منٹ',
          status: 'حیثیت',
        },
        statusMap: {
          Active: 'فعال',
          Inactive: 'غیر فعال',
        },
      },
      linesPage: {
        title: 'لائن اور ایکسٹینشن',
        button: 'لائن شامل کریں',
        createHeader: 'نئی لائن',
        tableHeaders: {
          lineName: 'لائن کا نام',
          extension: 'ایکسٹینشن',
          assignedTo: 'مقرر کیا گیا',
          status: 'حیثیت',
        },
        menuItems: {
          salesLine: 'سیلز لائن',
          supportLine: 'سپورٹ لائن',
        },
      },
      usersPage: {
        title: 'صارف',
        filterAll: 'سب',
        filterInterpreter: 'مترجم',
        filterCSR: 'CSR',
        filterCustomer: 'گاہک',
        filterWebManager: 'ویب مینیجر',
        createButton: 'نیا صارف بنائیں',
        createHeader: 'نیا بنائیں',
        newInterpreter: 'نیا مترجم',
        newCSR: 'نیا CSR',
        newManager: 'نیا منیجر',
        newCustomer: 'نیا گاہک',
        tableHeaders: {
          name: 'نام',
          email: 'ای میل',
          phone: 'فون',
          role: 'کردار',
          extension: 'ایکسٹینشن',
          language: 'زبان',
          status: 'حیثیت',
          edit: 'تدوین',
          delete: 'حذف',
        },
        formLabels: {
          fullName: 'پورا نام',
          emailAddress: 'ای میل پتہ',
          phoneNumber: 'فون نمبر',
          preferredLanguage: 'ترجیحی زبان',
          skill: 'مہارت',
          department: 'شعبہ',
          enterprise: 'ادارہ',
          gender: 'جنس',
          requestGender: 'درخواست کردہ جنس',
        },
        buttons: {
          cancel: 'منسوخ کریں',
          submit: 'جمع کریں',
          back: 'واپس',
          submitRequest: 'درخواست جمع کریں',
        },
        toast: {
          interpreter: 'مترجم کی درخواست جمع ہو گئی',
          csr: 'CSR کی درخواست جمع ہو گئی',
          manager: 'منیجر کی درخواست جمع ہو گئی',
          customer: 'گاہک کی درخواست جمع ہو گئی',
        },
      },
      historyPage: {
        pageTitle: {
          interpreter: 'Interpreter’s History',
          csr: 'CSR’s History',
          customer: 'Customer’s History',
          webManager: 'Web Manager',
          mobileInterpreter: 'Mobile Interpreter History',
          mobileManager: 'Mobile Manager History',
        },
        historyFilterButton: 'History',
        dropdown: {
          interpreter: 'Interpreter’s History',
          csr: 'CSR’s History',
          customer: 'Customer’s History',
          webManager: 'Web Manager',
          mobileInterpreter: 'Mobile Interpreter History',
          mobileManager: 'Mobile Manager History',
        },
        tableHeaders: {
          enterprise: 'Enterprise',
          dateTime: 'Date & Time',
          accessCode: 'Access Code',
          phone: 'Phone',
          language: 'Language',
          duration: 'Duration',
          edit: 'Edit',
          delete: 'Delete',
        },
        editModal: {
          title: 'Edit history record',
          enterprise: 'Enterprise',
          dateTime: 'Date & Time',
          accessCode: 'Access Code',
          phone: 'Phone',
          language: 'Language',
          duration: 'Duration',
          cancel: 'Cancel',
          saveChanges: 'Save Changes',
        },
        pagination: {
          page: 'Page',
        },
      },
      addInterpreterPage: {
        title: 'Add New Interpreter / CSR',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        requestType: 'Request Type',
        preferredLanguage: 'Preferred Language',
        skill: 'Skill',
        requestGender: 'Request Gender',
        back: 'Back',
        submitRequest: 'Submit Request',
      },
      addCSRPage: {
        title: 'Add New CSR',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        gender: 'Gender',
        back: 'Back',
        addCSR: 'Add CSR',
      },
      addManagerPage: {
        title: 'Add New Manager',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        department: 'Department',
        language: 'Language',
        gender: 'Gender',
        back: 'Back',
        addManager: 'Add Manager',
      },
      addCustomerPage: {
        title: 'Add New Customer',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        enterprise: 'Enterprise',
        preferredLanguage: 'Preferred Language',
        back: 'Back',
        addCustomer: 'Add Customer',
      },
      editInterpreterPage: {
        title: 'Edit Interpreter / CSR',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        requestGender: 'Request Gender',
        back: 'Back',
        saveChanges: 'Save Changes',
      },
      editCSRPage: {
        title: 'Edit CSR',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        language: 'Language',
        skill: 'Skill',
        gender: 'Gender',
        back: 'Back',
        saveChanges: 'Save Changes',
      },
      editManagerPage: {
        title: 'Edit Manager',
        fullName: 'Full Name',
        emailAddress: 'Email',
        phoneNumber: 'Phone Number',
        department: 'Department',
        language: 'Language',
        gender: 'Gender',
        back: 'Back',
        saveManager: 'Save Manager',
      },
    },
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
    const stored = window.localStorage.getItem(STORAGE_KEY) as LanguageCode | null;
    return stored && uiLabels[stored] ? stored : DEFAULT_LANGUAGE;
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(STORAGE_KEY, language);
    }
  }, [language]);

  const setLanguage = (value: LanguageCode) => {
    if (uiLabels[value]) {
      setLanguageState(value);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextValue => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
